apiVersion: apps/v1
kind: Deployment
metadata: 
  name: employee-management-api-deployment
  labels: 
    app: employee-management
    tier: backend
spec: 
  template: 
    metadata: 
      name: employee-management-api-pod
      labels: 
        app: employee-management
        tier: backend
    spec: 
      containers: 
        - 
          name: employee-management-api-container
          image: docker.io/cloudblockandbeyond/employee-management-api:1.0.0
          ports:
            - 
              protocol: TCP
              containerPort: 80
          resources: 
            requests: 
              memory: "64Mi"
              cpu: "250m"
            limits: 
              memory: "128Mi"
              cpu: "500m"
  replicas: 1
  selector: 
    matchLabels: 
      app: employee-management
      tier: backend